service: Blog1
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-north-1

functions:
  serverRoot:
    handler: app.server

    events:
      - http: #event trigger for the root route of an API Gateway HTTP
          path: /
          method: ANY # accept any HTTP method
          cors: true
  
      - http:
          path: /{proxy+}
          method: ANY #Accept any HTTP method
          cors: true

