name: lambda-deployment-with-github-action-test

on: 
  push:
    branches:
        main # You can use any of your root or master branch name
  
jobs:
  lambda-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v2

      - name: Setup node environment
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
          
      - name: Install serverless globally
        run: npm install -g serverless
      
      - name: Configure serverless authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY }} --secret ${{ secrets.AWS_SECRET_KEY }}

      - name: Install npm dependencies
        working-directory: ./api
        run: npm ci

      - name: Print working directory
        run: |
          pwd

      # - name: create aws-nodejs template
      #   run: sls create --template aws-nodejs --path api
        
      - name: Deploy lambda function
        working-directory: ./api
        run: sls deploy
